### ISSUE TITLE
Anilist link not formatted correctly

### ISSUE THREAD

**Issue by Nquxii** [HyphenSam/HyphenSam#1]
https://github.com/HyphenSam/HyphenSam/blob/6618937626281596dbefcebd82c6266702114b0e/README.md?plain=1#L23

should include `https`

i.e. `  - [AniList](https://anilist.co/user/HyphenSam/)`

**Comment by HyphenSam** [comment]
Whoops, thanks. Was copy/pasting from my GitHub bio.
